INSERT INTO amgrh.departements(nom,abbreviation,parent) VALUES 
('Division des Archives des Administrations Centrales et des Etablissements Publics','DAACEP',NULL),
('Division des Affaires Administratives et Financières','DAAF',NULL),
('Division de la Communication et de la Diffusion','DCD',NULL),
('Division de la Collecte et Traitement','DCT',NULL),
('Service des Archives des Administrations Centrales ','SAAC',1),
('Service des Archives des Etablissements publics','SAEP',1),
('Service de Gestion des Ressources humaines','SGRH',2),
('Service du Budget et Comptabilité','SBC',2),
('Service Production et Développement Informatique','SPDI',2),
('Service de Recherche Documentaire et Consultation','SRDC',3),
('Service de Publication et Edition','SPE',3),
('Service des Activités Culturelles et Scientifiques','SACS',3),
('Service des Méthodes et Normalisation','SMN',4),
('Service de la Collecte','SC',4),
('Service du Traitement','ST',4);