INSERT INTO amgrh.grades(nom, echelle, Cadre ) VALUES 
  ('Professeurs de l\'enseignement suppérieur', NULL, NULL),
  ('Administrateurs', NULL, NULL),
  ('Ingénieurs d\'etat', NULL, NULL),
  ('Techniciens', NULL, NULL),
  ('Assistants techniques', NULL, NULL),
  ('Assistants administratifs', NULL, NULL),
  ('Professeurs de l\'enseignement suppérieur grade C', 99, 1),
  ('Professeurs de l\'enseignement suppérieur grade B', 99, 1),
  ('Professeurs de l\'enseignement suppérieur grade A', 99, 1),
  ('Administrateur 1er grade', 99, 2),
  ('Administrateur 2ème grade', 11, 2),
  ('Administrateur 3ème grade', 10, 2),
  ('Ingénieur d\'etat principal', 11, 3),
  ('Ingénieur d\'etat 1er grade', 11, 3),
  ('Technicien 1er grade', 11, 4),
  ('Technicien 2ème grade', 10, 4),
  ('Technicien 3ème grade', 9, 4),
  ('Technicien 4ème grade', 8, 4),
  ('Assistant technique 1er  grade', 8, 5),
  ('Assistant technique 2ème  grade', 7, 5),
  ('Assistant technique 3ème  grade', 6, 5),
  ('Assistant administratif 1er  grade', 8, 6),
  ('Assistant administratif 2ème  grade', 7, 6),
  ('Assistant administratif 3ème  grade', 6, 6);
  